language: java

addons:
  sonarcloud:
    organization: "sabrinajebabli-github"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  -Dsonar.organization=sabrinajebabli-github  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.projectKey=com.ipiecoles.java.java340 -Dsonar.branch=master